// WeaponTypes.h
//
#pragma once

#include "XmlLib\SaxContentElement.h"

// Special note - The  "Unknown" entries of each enum must be entry 0 in the
// enum map as this is used by the SAX loaders to check for badly loaded values
// these enumerations are used across multiple object types

// specific weapon types
enum WeaponType
{
    Weapon_Unknown = 0,
    Weapon_All,
    Weapon_BastardSword,
    Weapon_BattleAxe,
    Weapon_Club,
    Weapon_Dagger,
    Weapon_Dart,
    Weapon_DwarvenAxe,
    Weapon_Falchion,
    Weapon_GreatCrossbow,
    Weapon_GreatAxe,
    Weapon_GreatClub,
    Weapon_GreatSword,
    Weapon_HandAxe,
    Weapon_Handwraps,
    Weapon_HeavyCrossbow,
    Weapon_HeavyMace,
    Weapon_HeavyPick,
    Weapon_Kama,
    Weapon_Khopesh,
    Weapon_Kukri,
    Weapon_LightCrossbow,
    Weapon_LightHammer,
    Weapon_LightMace,
    Weapon_LightPick,
    Weapon_Longbow,
    Weapon_Longsword,
    Weapon_Maul,
    Weapon_Morningstar,
    Weapon_Quarterstaff,
    Weapon_Rapier,
    Weapon_RepeatingHeavyCrossbow,
    Weapon_RepeatingLightCrossbow,
    Weapon_Scimitar,
    Weapon_Shortbow,
    Weapon_Shortsword,
    Weapon_Shuriken,
    Weapon_Sickle,
    Weapon_ThrowingAxe,
    Weapon_ThrowingDagger,
    Weapon_ThrowingHammer,
    Weapon_Unarmed,
    Weapon_Warhammer,
    // special types that are not specific weapons but work the same
    Weapon_ShieldBuckler,
    Weapon_ShieldSmall,
    Weapon_ShieldLarge,
    Weapon_ShieldTower,
    Weapon_Orb,
    Weapon_RuneArm,
    Weapon_Count,           // must be last entry
};
const XmlLib::enumMapEntry<WeaponType> weaponTypeMap[] =
{
    {Weapon_Unknown, L"Unknown"},
    {Weapon_All, L"All"},
    {Weapon_BastardSword, L"Bastard Sword"},
    {Weapon_BattleAxe, L"Battle Axe"},
    {Weapon_Club, L"Club"},
    {Weapon_Dagger, L"Dagger"},
    {Weapon_Dart, L"Dart"},
    {Weapon_DwarvenAxe, L"Dwarven Axe"},
    {Weapon_Falchion, L"Falchion"},
    {Weapon_GreatCrossbow, L"Great Crossbow"},
    {Weapon_GreatAxe, L"Great Axe"},
    {Weapon_GreatClub, L"Great Club"},
    {Weapon_GreatSword, L"Great Sword"},
    {Weapon_HandAxe, L"Hand Axe"},
    {Weapon_Handwraps, L"Handwraps"},
    {Weapon_HeavyCrossbow, L"Heavy Crossbow"},
    {Weapon_HeavyMace, L"Heavy Mace"},
    {Weapon_HeavyPick, L"Heavy Pick"},
    {Weapon_Kama, L"Kama"},
    {Weapon_Khopesh, L"Khopesh"},
    {Weapon_Kukri, L"Kukri"},
    {Weapon_LightCrossbow, L"Light Crossbow"},
    {Weapon_LightHammer, L"Light Hammer"},
    {Weapon_LightMace, L"Light Mace"},
    {Weapon_LightPick, L"Light Pick"},
    {Weapon_Longbow, L"Longbow"},
    {Weapon_Longsword, L"Longsword"},
    {Weapon_Maul, L"Maul"},
    {Weapon_Morningstar, L"Morningstar"},
    {Weapon_Quarterstaff, L"Quarterstaff"},
    {Weapon_Rapier, L"Rapier"},
    {Weapon_RepeatingHeavyCrossbow, L"Repeating Heavy Crossbow"},
    {Weapon_RepeatingLightCrossbow, L"Repeating Light Crossbow"},
    {Weapon_Scimitar, L"Scimitar"},
    {Weapon_Shortbow, L"Shortbow"},
    {Weapon_Shortsword, L"Shortsword"},
    {Weapon_Shuriken, L"Shuriken"},
    {Weapon_Sickle, L"Sickle"},
    {Weapon_ThrowingAxe, L"Throwing Axe"},
    {Weapon_ThrowingDagger, L"Throwing Dagger"},
    {Weapon_ThrowingHammer, L"Throwing Hammer"},
    {Weapon_Unarmed, L"Unarmed"},
    {Weapon_Warhammer, L"Warhammer"},
    // special types
    {Weapon_ShieldBuckler, L"Buckler"},
    {Weapon_ShieldSmall, L"Small Shield"},
    {Weapon_ShieldLarge, L"Large Shield"},
    {Weapon_ShieldTower, L"Tower Shield"},
    {Weapon_Orb, L"Orb"},
    {Weapon_RuneArm, L"RuneArm"},
    {WeaponType(0), NULL}
};
